# Generated by Django 6.0.2 on 2026-03-01 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
            options={
                'verbose_name': '处理模型',
                'db_table': 'ship_processing',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=128, verbose_name='bucket')),
                ('object_key', models.CharField(max_length=512, verbose_name='object_key')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'ship_image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=64, verbose_name='快递单号')),
                ('style', models.JSONField(blank=True, default=dict, verbose_name='样式与槽位定义')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_orders', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'ship_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='槽位内顺序')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_images', to='core.image', verbose_name='图片')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_images', to='core.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单图片',
                'db_table': 'ship_order_image',
                'ordering': ['order', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('style', models.JSONField(blank=True, default=dict, verbose_name='样式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_order_styles', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单样式模板',
                'db_table': 'ship_order_style',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.processing', verbose_name='处理模型')),
            ],
            options={
                'verbose_name': '处理配置项',
                'db_table': 'ship_processing_field',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512, verbose_name='分享链接或 token')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_share_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '分享链接',
                'db_table': 'ship_share',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='token')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_share_permissions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_permissions', to='core.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '分享权限',
                'db_table': 'ship_share_permission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_texts', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '文字',
                'db_table': 'ship_text',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='槽位内顺序')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_texts', to='core.order', verbose_name='订单')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_texts', to='core.text', verbose_name='文字')),
            ],
            options={
                'verbose_name': '订单文字',
                'db_table': 'ship_order_text',
                'ordering': ['order', 'position', 'id'],
            },
        ),
    ]
