# Generated by Django 6.0.2 on 2026-03-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderimage',
            options={'ordering': ['order', 'key', 'position', 'id'], 'verbose_name': '订单图片'},
        ),
        migrations.AlterModelOptions(
            name='ordertext',
            options={'ordering': ['order', 'key', 'position', 'id'], 'verbose_name': '订单文字'},
        ),
        migrations.AddField(
            model_name='orderimage',
            name='key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='槽位 key'),
        ),
        migrations.AddField(
            model_name='ordertext',
            name='key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='槽位 key'),
        ),
    ]
