# Generated by Django 6.0.2 on 2026-03-02 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_slot_key_to_order_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepermission',
            name='order',
            field=models.ForeignKey(blank=True, help_text='为空时表示该 token 允许访问创建者的所有订单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_permissions', to='core.order', verbose_name='订单'),
        ),
    ]
