# Generated by Django 6.0.2 on 2026-03-02 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_share_permission_order_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button_reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="按钮反转",
                        help_text="用于记录某个按钮的喜好状态（开/关）",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="core_user_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "db_table": "ship_user_preference",
                "verbose_name": "用户喜好",
            },
        ),
    ]

