# Generated by Django 6.0.2 on 2026-03-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_order_style',
            field=models.ForeignKey(blank=True, help_text='用户新建订单时默认选用的 OrderStyle；为空表示未设置默认样式', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='core.orderstyle', verbose_name='默认订单样式'),
        ),
    ]
