# Generated by Django 6.0.2 on 2026-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userpreference_default_order_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单成本', max_digits=12, null=True, verbose_name='成本'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单售价', max_digits=12, null=True, verbose_name='售价'),
        ),
    ]
