# Generated by Django 6.0.2 on 2026-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='订单是否已经完成', verbose_name='是否完成'),
        ),
    ]
