# Generated by Django 6.0.2 on 2026-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_style_id',
            field=models.IntegerField(blank=True, help_text='记录创建订单时使用的 OrderStyle.id', null=True, verbose_name='创建样式 ID'),
        ),
    ]
