# Generated by Django 6.0.2 on 2026-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_create_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(blank=True, help_text='订单标记为已完成的时间', null=True, verbose_name='完成时间'),
        ),
    ]
