# Generated by Django 6.0.2 on 2026-03-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_order_completed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='allow_tracking_lookup',
            field=models.BooleanField(default=False, help_text='开启后，他人可通过快递单号完全匹配方式查看该用户订单的只读页面', verbose_name='允许通过快递单号查看订单'),
        ),
    ]
