# Generated by Django 6.0.2 on 2026-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tracking_lookup_key_replaces_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=10737418240, help_text='允许该用户存储的图片总大小（字节），默认 10GB', verbose_name='存储容量上限（字节）'),
        ),
    ]
