# Generated by Django 6.0.2 on 2026-03-03 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_order_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='客户名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_customers', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '客户',
                'db_table': 'ship_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fields', to='customer.customer', verbose_name='客户')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_field', to='core.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单客户关联',
                'db_table': 'ship_customer_order_field',
            },
        ),
    ]
