# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tracking_lookup_key',
            field=models.CharField(
                blank=True,
                help_text='用于通过 密钥+快递单号 查询该客户订单的只读权限',
                max_length=64,
                null=True,
                unique=True,
                verbose_name='订单查询密钥',
            ),
        ),
    ]
